name: flashlight
description: ""

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.11.3


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9

  #----------- UI -----------#
  gap: ^3.0.1
  flutter_svg: ^2.3.0
  lottie: ^3.5.1
  shimmer: ^4.0.0
  pinput: ^6.0.2
  table_calendar: ^3.2.1
  share_plus: ^13.3.0

  #----------- utils -----------#
  intl: ^0.20.2
  device_info_plus: ^13.2.0
  extended_image: ^10.1.0
  url_launcher: ^6.3.2
  dropdown_button2: ^3.1.0
  equatable: ^2.1.0
  image_picker: ^1.2.3
  permission_handler: ^13.0.1
  package_info_plus: ^10.2.1
  sensors_plus: ^6.1.1
  flutter_colorpicker: ^1.1.0
  wakelock_plus: ^1.8.0
  screen_brightness: ^2.1.11
  installed_apps: ^2.1.1


  #----------- notification -----------#
  flutter_local_notifications: ^22.3.0

  #----------- Storage services -----------#
  shared_preferences: ^2.5.5

  #----------- App update helper -----------#
  in_app_update: ^5.0.0
  upgrader: ^13.7.0

  #----------- state management -----------#
  provider: ^6.1.5+1

  #----------- connectivity Checker -----------#
  connectivity_plus: ^7.3.1

  #----------- localization -----------#
  flutter_localizations:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  #----------- auto generators -----------#
  build_runner: ^2.15.1
  flutter_gen_runner: ^5.15.0


#----------- asset generator configuration ----------#
flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
    lottie: true


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/language/
    - assets/images/other_apps/
    - assets/json/
    - assets/icons/language/
    - assets/icons/
    - assets/lotties/


  fonts:
      - family: Roboto
        fonts:
          - asset: assets/fonts/roboto/Roboto-Thin.ttf
            weight: 100
          - asset: assets/fonts/roboto/Roboto-Light.ttf
            weight: 300
          - asset: assets/fonts/roboto/Roboto-Regular.ttf
            weight: 400
          - asset: assets/fonts/roboto/Roboto-Medium.ttf
            weight: 500
          - asset: assets/fonts/roboto/Roboto-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/roboto/Roboto-Bold.ttf
            weight: 700
          - asset: assets/fonts/roboto/Roboto-ExtraBold.ttf
            weight: 800
          - asset: assets/fonts/roboto/Roboto-Black.ttf
            weight: 900

flutter_intl:
  enabled: true
  use_deferred_loading: true